#Configuation for robot odometry EKF
#
frequency: 50

odom0: /jackal_velocity_controller/odom
#Henry Wilson: According to clearpath's documentation, these matrices
#enable and disable various measurements from the IMU and for the odom
#coordinate frame.
#
#xyz
#rpy
#lateral vel
#rotatio vel
#lateral acc

#This affects odom/filtered
odom0_config: [false, false, false,
               true, true, true,
               true, true, true,
               true, true, true,
               true, true, true]
odom0_differential: false

#IMU's relevant data
imu0: /imu/data
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              false, false, false]
imu0_differential: false

odom_frame: odom
base_link_frame: base_link
world_frame: odom
